version: '3.7'

networks:
  app-network:
    driver: bridge

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
      target: base
    networks:
      - app-network
    volumes:
      - .:/app:rw,cached

  database:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    networks:
      - app-network
    ports:
      - 3306:3306
