name: 'Build'

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APP_ENV: 'test'
  APP_RELEASE: 'unknown'
  PHP_VERSION: 8.1
  PHP_EXTENSIONS: 'intl'
  PHP_TOOLS: 'composer:v2, psalm, cs2pr'

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Get build version'
        id: version
        shell: bash
        run: |
          echo "::group::Get build version"
          set +e
          tag="$(git describe --tags "$(git rev-list --tags --max-count=1)" 2>/dev/null)"
          tag="${tag/v/}"
          if [ -z "${tag}" ]; then
            tag="0.0.0"
          fi
          release="${tag}-$(git rev-parse --short HEAD)"
          set -e
          echo "APP_RELEASE=${release}" >> $GITHUB_ENV
          echo "::endgroup::"

          # set application environment
          echo "::group::Create .env.local"
          echo "APP_ENV=${APP_ENV}" >> .env.local
          echo "APP_RELEASE=${release}" >> .env.local
          echo "::endgroup::"

      - name: 'Setup PHP with Xdebug'
        id: setup-php
        uses: shivammathur/setup-php@2.7.0
        with:
          coverage: xdebug
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          tools: ${{ env.PHP_TOOLS }}

      - name: 'Install Symfony CLI'
        run: |
          echo "::group::installer symfony cli"
          wget https://get.symfony.com/cli/installer -O - | bash
          echo "::endgroup::"
          echo "::group::Check if any dependencies are compromised"
          /home/runner/.symfony/bin/symfony check:security
          echo "::endgroup::"

      - name: 'Get composer cache directory'
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: 'Cache dependencies'
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php-version }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php-version }}-composer-

      - name: 'Install dependencies'
        id: install
        run: |
          echo "::group::composer validate"
          composer validate --strict
          echo "::endgroup::"
          echo "::group::composer install"
          composer install --prefer-dist --no-interaction --optimize-autoloader --quiet
          echo "::endgroup::"
          echo "::group::composer dump environment variables"
          composer dump-env ${{ env.APP_ENV }}
          echo "::endgroup::"

      - name: 'Artifact: .env '
        uses: actions/upload-artifact@v2
        with:
          retention-days: 2
          name: build-dev
          path: |
            ./.env.local.php
