name: 'Test'

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: [ "Build" ]
    branches: [ main, develop ]
    types: [ completed ]

jobs:
  test:
    name: 'Testing'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Run PHPStan static analysis tool'
        continue-on-error: true
        run: php ./vendor/bin/phpstan analyse ./src --error-format=checkstyle | cs2pr

      #      - name: 'Run Psalm'
      #        continue-on-error: true
      #        run: psalm --output-format=github

      - name: 'Run PHPUnit testing'
        continue-on-error: true
        run: php ./bin/phpunit --testdox --colors=always

      - name: 'Run mutation testing '
        continue-on-error: true
        run: php ./vendor/bin/infection --coverage=public/reports/infection

      - name: 'Artifact: build reports'
        uses: actions/upload-artifact@v2
        with:
          retention-days: 2
          name: build-reports
          path: |
            ./public/reports/*